function stress=get_stress_real(strain,type)

MAT.Uel=[4.154766e-12, 1098.0, 35000000.0, 0.15, 0.15, 1.05, 0.05, 1.2e+11, ...
    0.25, 1.07317, 5.0, 1.0, 0.05, 0.3, 0.1, 1.0, 14836;
    9.62115e-12, 1098.0, 160000000.0, 0.15, 0.025, 0.195, 0.006, 3.13e+11, ...
    0.25, 1.03264, 3.0, 0.35, 0.035, 0.65, 0.5, 0.19, 14836];

if type==1
    prop_mat=MAT.Uel(1,:);
else
    prop_mat=MAT.Uel(2,:);
end
    Es=prop_mat(3);
    alfa0=prop_mat(4);
    C1=prop_mat(5);
    C2=prop_mat(6);
    C3=prop_mat(7);
    Eh=prop_mat(8);
    Xi=prop_mat(10);
    Beta=prop_mat(11);
    Gamma0=prop_mat(12);
    Delta=prop_mat(13);

%     Epsimax=strain-1e-10;
    Epsimax=strain;
    Epsimax(Epsimax<0)=0;  
%     P1=zeros(length(strain),1);
    P1=0*strain;
    
    P1(Delta>=strain)=Eh*((strain(Delta>=strain)*sqrt(pi)*Xi*erf(sqrt(Beta)*(Delta-Gamma0)))/ ...
    (2.*sqrt(Beta)) - ...
    (strain(Delta>=strain).*sqrt(pi)*Xi.*erf(sqrt(Beta)*(strain(Delta>=strain) - Gamma0)))/ ...
    (2.*sqrt(Beta)));
    
    P4= exp(-(Beta*(Delta + strain - Gamma0).^2));
    P5= exp(-(Beta*(-Gamma0 + max(Delta,strain)).^2));
    P6= erf(sqrt(Beta)*(Delta + strain - Gamma0));
    P7= sqrt(Beta*pi)*(Delta + strain - Gamma0);
%     P8= sqrt(Beta)*(Delta + strain - Gamma0)*sqrt(pi);
    P9= erf(sqrt(Beta)*(-Gamma0 + max(Delta,strain)));
    P2=Eh*(Xi/(2.*Beta))*(P4-P5+P7.*(P6-P9));
%% problem    
    P3=Es*(alfa0 + (sqrt(pi)*Xi*erf(sqrt(Beta)*(strain - Gamma0)))/ ...
    (2.*sqrt(Beta)) + (sqrt(pi)*Xi*erf(sqrt(Beta)*Gamma0)) ...
    /(2.*sqrt(Beta))).* ...
    (-0.25 + strain./ ...
    (C1 + C2* ...
    (alfa0 + (sqrt(pi)*Xi*erf(sqrt(Beta)*(strain - Gamma0)))/ ...
    (2.*sqrt(Beta)) + (sqrt(pi)*Xi*erf(sqrt(Beta)*Gamma0))/(2.*sqrt(Beta))).^C3) + 0.25./ ...
    (1 - strain./ ...
    (C1 + C2*(alfa0 + (sqrt(pi)*Xi*erf(sqrt(Beta)*(strain - Gamma0)))/ ...
    (2.*sqrt(Beta)) + (sqrt(pi)*Xi*erf(sqrt(Beta)*Gamma0))/ ...
    (2.*sqrt(Beta))).^C3)).^2);
%% problem end        
    stress_new=P1+P2+P3;

%     P2=zeros(length(Epsimax),1);  
    P2=0*Epsimax;
    P2(Delta>=Epsimax) =(strain(Delta>=Epsimax)*sqrt(pi)*Xi*erf(sqrt(Beta)*(Delta - Gamma0)))/(2*sqrt(Beta))- ...
    (strain(Delta>=Epsimax)*sqrt(pi)*Xi.* ...
    erf(sqrt(Beta)*(Epsimax(Delta>=Epsimax) - Gamma0)))/(2.*sqrt(Beta));
    
%     P1=zeros(length(strain),1);
    P1=0*strain;
    ind_p1 = (Delta+strain > max(Epsimax,Delta)); 

    P1(ind_p1)=(Xi*(exp((-Beta)*(Delta + strain(ind_p1) - Gamma0).^2) ...
    + sqrt(Beta).*(Delta + strain(ind_p1) - Gamma0)*sqrt(pi) ...
    .*erf(sqrt(Beta)*(Delta+strain(ind_p1) - Gamma0))))./ ...
    (2*Beta)-(Xi*(exp((-Beta)*(max(Epsimax(ind_p1),Delta) - Gamma0).^2) ...
    +sqrt(Beta)*(Delta + strain(ind_p1) - Gamma0)*sqrt(pi) ...
    .*erf(sqrt(Beta)*(max(Epsimax(ind_p1),Delta) - Gamma0))))/(2*Beta);         

    stress_new2=Es*(alfa0 + (sqrt(pi)*Xi*erf(sqrt(Beta)*(Epsimax - Gamma0)))/...
    (2.*sqrt(Beta)) + (sqrt(pi)*Xi*erf(sqrt(Beta)*Gamma0))/(2.*sqrt(Beta))) .* ...
    (-0.25 + strain./(C1 + C2*(alfa0 + (sqrt(pi)*Xi*erf(sqrt(Beta) ...
    *(Epsimax - Gamma0)))/(2.*sqrt(Beta)) + (sqrt(pi)*Xi ... 
    *erf(sqrt(Beta)*Gamma0))/(2.*sqrt(Beta))).^C3) + 0.25./(1 ...
    -strain./(C1 + C2*(alfa0 + (sqrt(pi)*Xi*erf(sqrt(Beta) ... 
    *(Epsimax - Gamma0)))/(2.*sqrt(Beta)) + (sqrt(pi)*Xi ...
    *erf(sqrt(Beta)*Gamma0))/(2*sqrt(Beta))).^C3)).^2) + Eh*(P1+P2);             
        
    stress=max(stress_new,stress_new2);                             
end


